### ISSUE TITLE
Attributes data don't get deleted when we delete a Model

### ISSUE THREAD

**Issue by Rukhsar** [sunel/eav#13]
@sunel, when we delete a model, say we delete a product, any attributes attached for that product like name, SKU (saved in varchar table) don't get deleted.

It just deletes the Product model, not all the footprints.

I think this fix will help people to keep their database clean. Let me know if this one is possible.

Thanks

**Comment by sunel** [comment]
@Rukhsar 

I have tested this, seems like its working as expected. The Attributes data is getting deleted when the model is deleted.

We already have delete cascade for every attribute table.

https://github.com/sunel/eav/blob/2d853c79eb5dcb2e3ab1627ba900b8158eb98f96/tests/migrations/2018_08_05_054603_create_product_entity_table.php#L29-L33

**Comment by Rukhsar** [comment]
How you delete a model because when I deleted my model it doesn't clean up all tables data?

**Comment by sunel** [comment]
@Rukhsar 

```php
$product = Products::find(1);

$product->delete();
```
