### ISSUE TITLE
Too many tables; MySQL can only use 61 tables in a join 

### ISSUE THREAD

**Issue by Rukhsar** [sunel/eav#16]
@sunel we are using your package and we are nearly there with our project. Just found an issue when you assign 60+ attributes to a product or model we are getting the following problem upon saving or updating the product.

`SQLSTATE[HY000]: General error: 1116 Too many tables; MySQL can only use 61 tables in a join (SQL: select `bikes`.`id`, `details_gallery_attr`.`value` as `details_gallery`, `geometry_gallery_attr`.`value` as `geometry_gallery`, `hero_gallery_attr`.`value` as `hero_gallery`, `image_attr`.`value` as `image`, .............`

I think you have to refine the query to save only attributes provided not all the attributes.

Can you please look at this as its urgent.

Thanks

**Comment by sunel** [comment]
Can you post the model or the way the you are fetching the data.

**Comment by Rukhsar** [comment]
I am fetching the model as 
`$bike = Bike::where('id', $id)->select($attributes)->first();`

where `$attributes` is an array of attributes I want to grab for the bike. This part works fine. 

When I do 

`$bike->update($request->all());` it breaks.

It through error that only 61 tables are allowed in a join. I think the problem is when we are trying to save the model its trying to assign the values to all attributes, not just the ones are passed through `$request` object.

I have completed my project and was doing the testing for adding as many as attributes and it just didnt worked for me.

Thanks

**Comment by sunel** [comment]
```php
$bike->update($request->all());
```
its a [mass update](https://sunel.github.io/eav/master/model.html#mass-updates) case.

Can you try this if you are just updating a single entity

```php
$bike->fill($request->all());
$bike->update();
```

**Comment by sunel** [comment]
Sorry 

```php
$bike->fill($request->all());
$bike->save();
```

**Comment by sunel** [comment]
Hope you have the latest code

**Comment by sunel** [comment]
You can also take a look at [Flat table](https://sunel.github.io/eav/master/ideology/flat-table.html)

**Comment by sunel** [comment]
@Rukhsar 

Made few changes based, now i think `$bike->update($request->all());` too will work as expected.

**Comment by sunel** [comment]
@Rukhsar 

Now by default sub selects are used to fetch the attributes values. I have tested with 3000 attributes.

Can you pull the latest code and test if its works for you.

**Comment by Rukhsar** [comment]
hi Sunel,

Thanks for updating me. I will be testing our system to check the 61 tables issue. Will let you know when its fully tested.

Thanks

**Comment by Rukhsar** [comment]
@sunel I have tested on 85 attributes and its working now. 

If I have any issue I will let you know. Closing this issue for now.
