### ISSUE TITLE
bigInteger Table name problem

### ISSUE THREAD

**Issue by sinamiandashti** [sunel/eav#17]
Hello

i have a bigInteger attribute assigned to my entity

when try to insert a new row to DB of that entity
it tries to insert to **product_item_biginteger**    instead of **product_item_biginteger**
the I should be uppercase
and it result this exception

>     Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'iranrentercore.product_item_biginteger' doesn't exist (SQL: insert into `product_item_biginteger` (`entity_type_id`, `attribute_id`, `entity_id`, `value`) values (2, 20, 1, 3460528))
> 
>   at /home/sinamiandashti/projects/iranrenter/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
>     660|         // If an exception occurs when attempting to run a query, we'll format the error
>     661|         // message to include the bindings with SQL, which will make this exception a
>     662|         // lot more helpful to the developer instead of just the database's errors.
>     663|         catch (Exception $e) {
>   664|             throw new QueryException(
>     665|                 $query, $this->prepareBindings($bindings), $e
>     666|             );
>     667|         }
>     668|

**Comment by sinamiandashti** [comment]
btw
it happens after upgrade to laravel 5.7

**Comment by sunel** [comment]
Seem like the issue due the addition of this code

https://github.com/sunel/eav/blob/5cbd0a11d850584881dfb66807fe2fc4adcd2625/src/Attribute.php#L378

Right now you can rename the table to all lower case, this will be final.

I will be adding the strtolower here also

https://github.com/sunel/eav/blob/5cbd0a11d850584881dfb66807fe2fc4adcd2625/src/Migrations/EntityMigrationCreator.php#L134

**Comment by sinamiandashti** [comment]
thx
