### ISSUE TITLE
How to develop a products filter with multiple attributes and tags

### ISSUE THREAD

**Issue by joaopmmartins** [sunel/eav#21]
I am developing a products listing page, which has a filter sidebar for attributes and tags. The filter is based  on checkboxes and users can select multiple filters.

Filter by Width:
----------------
30cm (12 products)
20 cm (3 products)

Filter by Weight:
------------------
2 Kg (3 products)
12 Kg (6 products)

Filter by Tags:
---------------
Outdoor Seating ( 4 products)
Long Handled Equipment ( 12 counts)

my product model has the following relationship:

public function attributes() {
        return $this->hasMany('Eav\Attribute', 'entity_id');
}

public function categories() {
        return $this->belongsToMany('App\Category', 'category_product', 'product_id', 'category_id');
}

public function tags() {
        return $this->belongsToMany('App\Tag', 'product_tag');
}

I have the following function in my product model,  to filter the category products on attributes and tags:

public function scopeFilter($q) {

        // filter on EAV attributes 
        $filter = request('filter');
        foreach ($filter as $filter_code => $values) :
                    $q->whereInAttribute($filter_code, $values);
        endforeach;

       // filter on tags
       $tags = request('tag');
        $q->whereHas('tags', function ($query) use ($tags) {
                    $query->whereIn('slug', $tags);
        });
       ......

        return $q;
}

Can you advise me how to develop such a function to get the eloquent query to return selected EAV attributes OR (not AND) selected tags?

Many Thanks.

**Comment by sunel** [comment]
Ref https://github.com/sunel/eav/issues/22#issuecomment-445520605

For the start and i will walk you based on our need

**Comment by joaopmmartins** [comment]
Can you advise me how I filter the products to show selected 'tags' OR selected 'attributes'?

**Comment by joaopmmartins** [comment]
The width and weight are EAV attributes but the tags are stored in a separated table.
How can I select all the products with attributes width=30cm OR weight=2Kg OR tagged with 'Outdoor Seating'? Can you point me in the right direction?

**Comment by joaopmmartins** [comment]
Hi Sunel,

The following query:

$products = Product::with('categories')->orWhereHas('categories', function ($query) {
                    $query->where('slug', request()->category);
                })->where('product.frontend_status', 1)->select(['attr.*'])
                  ->whereAttribute('garden_tool_type','=','cultivator')
                  ->whereAttribute(function ($query) {
                    $query->orWhereAttribute('garden_tool_material', '=', 'wooden');
                    $query->orWhereAttribute('garden_tool_material', '=', 'metal');
                    });	      
             //     ->orWhereAttribute('garden_tool_type','=','fork')

gives me the error: 'Illegal offset type'.

I just want to create a query with grouped AND and OR that does:

SELECT the products belonging to category of slug 'garden-tools' AND ( attribute 'garden_tool_type' = 'cultivator' OR garden_tool_material = 'wooden' OR garden_tool_material='metal' OR tag='css' OR tag ='js' ...... )?

**Comment by sunel** [comment]
@joaopmmartins 

Can you mention which line this error occurs.

i am sure this code your refering `request()->category` should be `request()->query('category')`

**Comment by sunel** [comment]
Closing this issue as we have #25 to track the bug
