### ISSUE TITLE
Products have many attributes (Color, Size ...)

### ISSUE THREAD

**Issue by TranDucBlog** [sunel/eav#22]
What do I need to insert multiple properties for each product, giving me an example of a product with multiple attributes, each with different price attributes. thank you

**Comment by sunel** [comment]
Can you give me a example, i will try to help you out

**Comment by TranDucBlog** [comment]
As in the documentation, I want to add attributes like "Color", "Size" ... to the data, how do I add them?
https://sunel.github.io/eav/master/model.html#inserting-updating-entity
```
Products::create([
    'name' => 'Flamethrower',
    'sku'  => '1HJK92',
    'upc'  => 'SHNDUU451888',
    'description' => 'Not a Flamethrower',
    'search' => 1
]);
```
The product "Flamethrower" has additional properties such as "Color", "Size", for example: Red + Size: L => Price 5000, Black + Size: L = > price 6000 ... I'm not sure how to save it and its operation, you can help me for example on adding new products with multiple attributes, each with different pricing attributes.

**Comment by sunel** [comment]
Sure, let me walk though.

- [ ] After installing the product and adding the provider the `app.php` [DOC](https://sunel.github.io/eav/master/installation.html)
- [ ] First run the migration this will create the base table that are required by the EAV package.
- [ ] Push the config by running the below [DOC](https://sunel.github.io/eav/master/configuration.html)

```bash
php artisan vendor:publish --tag="eav.config"
```
- [ ] Check the `fieldTypes` and add the types that you require.
- [ ] Now you need to create a entity, lets say it as `product`  [DOC](https://sunel.github.io/eav/master/ideology/entity.html)

```bash
php artisan eav:make:entity product \\App\\Products
```
- [ ] Next We need to create the attributes that are required [DOC](https://sunel.github.io/eav/master/ideology/attribute.html)
```bash
php artisan eav:make:attribute product --attributes sku:string,name:string,search:boolean,description:text
```
This is will create the migration that is needed to create the attibute and map it to the entity.
- [ ]  update migration if necessary like `backend_type`,`frontend_type` for the attributes
- [ ] run the migration.

Now you have a Entity `product` with a `Default` Set and `sku,name,search,description` attributes assigned to the Set under `General` group.

You can now do CRUD operations [DOC] (https://sunel.github.io/eav/master/model.html#introduction)

Here is [Set](https://sunel.github.io/eav/master/ideology/attribute-set.html) is a way you can segregate the attributes.

`product` is high level entity, lets say you have shop selling  kind of products `shirts` and `books`. Both will be having different kind of attributes. 

 Here you dont need to need to create another entity, sets can be used to for this purpose.

To create a new set `Eav\AttributeSet::create` [DOC](https://sunel.github.io/eav/master/ideology/attribute-set.html#add)

```php
$entity = Eav\Entity::findByCode('product');
Eav\AttributeSet::create([
    'attribute_set_name' => 'clothing',
    'entity_id' => $entity->entity_id,
]);

Eav\AttributeSet::create([
    'attribute_set_name' => 'books',
    'entity_id' => $entity->entity_id,
]);
```

To add the attributes to the sets
```php
Eav\EntityAttribute::map([
    'attribute_code' => 'size',
    'entity_code' => 'product',
    'attribute_set' => 'clothing',
    'attribute_group' => 'General'
]);

Eav\EntityAttribute::map([
    'attribute_code' => 'author',
    'entity_code' => 'product',
    'attribute_set' => 'books',
    'attribute_group' => 'General'
]);
```

Group are way to organized attributes are into groups in a set [DOC](https://sunel.github.io/eav/master/ideology/attribute-group.html#add).

```php
Eav\AttributeGroup::create([
    'attribute_group_name' => 'Metadata',
    'attribute_set_id' => $attributeSet->attribute_set_id,
]);
```

More to continue .....
