### ISSUE TITLE
error when using parameter grouping in query

### ISSUE THREAD

**Issue by joaopmmartins** [sunel/eav#25]
When I try the following query using parameter grouping :

`
$type1 = 'cultivator';
$type2 = 'fork';

$products = Product::whereAttribute('garden_tool_material', '=', 'wooden')
            ->whereAttribute(function (  $query) use ($type1, $type2) {
                    $query->whereAttribute('garden_tool_type', '=', $type1);
                    $query->orWhereAttribute('garden_tool_type', '=', $type2);
            })->get()
            ->select(['attr.*']);
`

I get the error:

 Illegal offset type

**Comment by sunel** [comment]
@joaopmmartins 

Can you check now i have made a fix for the issue

**Comment by joaopmmartins** [comment]
Sunel, many thanks for that.
