### ISSUE TITLE
How to retrieve one model with all attribute values.

### ISSUE THREAD

**Issue by RadoslavAngelov** [sunel/eav#3]
Hello,

how can you take a model instance with all its attribute values. For example I have Product with attribute name. If I want to update the value of name I can make:

`$product = Products::find(1);

$product->name = 'Not a Flamethrower';

$product->save();`

but how can I display `$product->name`. If i try to `dd($product->name)` the result is `null`

**Comment by sunel** [comment]
As  you can the name is a attribute , its not the member of the main table, so while retrieving the `name`, you need to tell the system that to include it

```php
Products::where('id', 1)->get('*', 'name');
```

`*` ->  to get all the values from the main table and `name` attributes to be included.

> Let me know if you find any issue understanding this, i am trying make the documentation more clear.

**Comment by RadoslavAngelov** [comment]
Yes, thank you this works.
