### ISSUE TITLE
Deleting old values when we change the attribute backend type from decimal to varchar

### ISSUE THREAD

**Issue by Rukhsar** [sunel/eav#30]
Hi,

So far your package is working very well. I just found an issue.

When we have already saved some values for an attribute in my case it's weight set to use the decimal table. But now we want to use the varchar values for this attribute as users want to enter weigh like 50kg or want to attach a note to weight.

I changed the backend table from decimal to varchar and stored the new values.

When we load the value for weight attribute it still refers to the decimal value. 

Is it possible to add a check in your package to delete the old value if a table type is changed?

Thanks

**Comment by sunel** [comment]
@Rukhsar 

Did you try Clearing the cache

https://github.com/sunel/eav/blob/master/src/Traits/Attribute.php#L67
