### ISSUE TITLE
CRUD operation for EAV

### ISSUE THREAD

**Issue by livevasiliy** [sunel/eav#31]
Hi @sunel 
How to made CRUD operation's use your package.
For example, how to make add new attribute use UI & Laravel Controller's. 

Thanks you.

**Comment by sunel** [comment]
@livevasiliy 

check https://github.com/sunel/eav/tree/master/tests/Feature or https://github.com/sunel/eav/tree/master/src/Api/Http/Controllers


Right now i am working on API you can check that too

https://github.com/sunel/eav/blob/master/routes/api.php

Note: API is Still in development
