### ISSUE TITLE
Get value attributes by BelongsToMany

### ISSUE THREAD

**Issue by livevasiliy** [sunel/eav#32]
Hi @sunel !

Can you help, I have two models. First `AdminProduct` - base model holds info about the product.
The second model - It's Eav model AttributeProducts. Below my source code.

AdminProduct model 

![image](https://user-images.githubusercontent.com/15705591/57768636-1dd89180-771d-11e9-9a09-6c4b11e2ef0e.png)

AttributeProducts model

![image](https://user-images.githubusercontent.com/15705591/57768684-3b0d6000-771d-11e9-9aab-978ed8f4257f.png)

And I have pivot table `admin_product_attr`
![image](https://user-images.githubusercontent.com/15705591/57768776-65f7b400-771d-11e9-90b1-dba3b1aa042e.png)

Now I want to find the product by id with all attributes attached to a single product.
I can get inverse by AttributeProducts all attributes & product.

**Comment by sunel** [comment]
@livevasiliy 

Check this https://github.com/sunel/eav/blob/master/tests/Feature/Issue10Test.php

If you still have issue let me know i will give more info

**Comment by livevasiliy** [comment]
It's not solutions to my case. I need via relationship `attrs` get all attributes. I expect in results get the object to hold data about product and object attrs hold list attributes attached to the product by id.
Your test-case the solution returned list attributes without data about model Designs.

If your use test-case I want to get list attributes model `Designs` use relationships `cars` return all value attributes attached to `Design` by id model `Design`

**Comment by sunel** [comment]
@livevasiliy 

If i am correct you don't require two seprate models.

`\Eav\Model` is extended from `\Illuminate\Database\Eloquent\Model` so you can use the `\Eav\Model` as regular model.

Now to your example

```php
class AdminProduct extends \Eav\Model
{
    const ENTITY  = 'admin_products';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = "admin_products";
}
```

in you db just update the `entity_code` field in `entities` table from `attrs` to `admin_products`;

Ref this https://sunel.github.io/eav/master/model.html#introduction

**Comment by livevasiliy** [comment]
@sunel 

I wanna separate on two models because of I doing API for my Front-end and to be easy my Front-end developer to understand where attributes this product.

**Comment by livevasiliy** [comment]
@sunel 

I made a decision. I will make a collection in which I will store the values that I will receive separately and will give this collection to the frontend.

**Comment by livevasiliy** [comment]
@sunel 

If I use model AdminProduct as Eav model. How I will handle creating new attributes because of my controller now creating products i.e I fill fields like name, barcode. Do I need me to create a new function in my controller via this function handle form for creating new attributes?

**Comment by sunel** [comment]
@livevasiliy

Yes
