### ISSUE TITLE
Update Method in Controllers

### ISSUE THREAD

**Issue by livevasiliy** [sunel/eav#34]
Hello, @sunel !

I write a controller to handle CRUD attributes. I get errors in the `edit` method.
`Eav\Attribute::code must return a relationship instance. (View: C:\OSPanel\domains\vpalette\resources\views\admin_product_attributes\fields.blade.php) (View: C:\OSPanel\domains\vpalette\resources\views\admin_product_attributes\fields.blade.php)`

![image](https://user-images.githubusercontent.com/15705591/58252623-9e2f7000-7d77-11e9-86ba-40192024e8ff.png)

Where `AttributeModel` it's `use Eav\Attribute as AttributeModel;`

How to correct made ?

**Comment by sunel** [comment]
@livevasiliy 

Seems like the issue is in the view, can you post the blade file ??

**Comment by livevasiliy** [comment]
@sunel 

https://1drv.ms/f/s!AiKdJriEUgPqgfcJrj84eDEoXZWfjg My source

**Comment by livevasiliy** [comment]
@sunel 

Why method `show` working a correct, but the `edit` method with the analogy code the `show` not work ??

**Comment by sunel** [comment]
@livevasiliy 

`code` is a method in the class `Eav\Attribute`, use  `attribute_code` in fields.blade.php Line No 22

**Comment by livevasiliy** [comment]
@sunel !

Hey, it's work! 
Thanks 😁👍👌
