### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by Rukhsar** [sunel/eav#39]
Hi,
Can you please update the package to support Laravel 6. I am getting the below error

`Call to undefined function Eav\Traits\array_get()`

Array and string helper functions are removed from the Laravel 6.

Can you please make an update to this package.

Thanks

**Comment by sunel** [comment]
@Rukhsar 

Fixed this in https://github.com/sunel/eav/commit/b0050043050b287e4c1f9c05d1d52213233fba02 and tagged new version
