### ISSUE TITLE
Model Event ignored

### ISSUE THREAD

**Issue by divdax** [sunel/eav#40]
I've an entity `App\Product` and using the [spatie/laravel-sluggable](https://github.com/spatie/laravel-sluggable) package to create a slug for each product.

The slug is defined as a static attribute and the column slug is available on the products table but when a product is created no slug is inserted.

Even with a basic boot method to listen for events on my Product model this is ignored:
```php
public static function boot()
{
    parent::boot();

    static::creating(function($data) {
        $data->slug = 'test';
    });
}
```

The core snippet from the package is using the magic boot mechanism like so:

**HasSlug Trait:**
```php
protected static function bootHasSlug()
{
    static::creating(function (Model $model) {
        $model->generateSlugOnCreate();
    });

    static::updating(function (Model $model) {
        $model->generateSlugOnUpdate();
    });
}
```

**Comment by sunel** [comment]
@divdax 

Have you mentioned `slug` as **Static Attribute**

https://sunel.github.io/eav/master/ideology/static-attribute.html

**Comment by divdax** [comment]
@sunel Yes, like i said in my post. 😄 
> The slug is defined as a static attribute and the column slug is available on the products table but when a product is created no slug is inserted.

Attributes table
<img width="698" alt="Bildschirmfoto 2020-01-19 um 10 52 17" src="https://user-images.githubusercontent.com/1456739/72678827-e3907280-3aa9-11ea-8c5a-706e09a31bab.png">

Products table
<img width="537" alt="Bildschirmfoto 2020-01-19 um 10 53 07" src="https://user-images.githubusercontent.com/1456739/72678832-e8edbd00-3aa9-11ea-8a61-004aef88ba3e.png">

**Comment by sunel** [comment]
@divdax 

Can you dump the data from `$mainData` from this line 

https://github.com/sunel/eav/blob/master/src/Model.php#L235

**Comment by divdax** [comment]
@sunel here the dump:
```php
array:7 [
  "name" => "test"
  "slug" => null
  "description" => "asd"
  "attribute_set_id" => 1
  "entity_id" => 1
  "updated_at" => "2020-01-22 00:08:39"
  "created_at" => "2020-01-22 00:08:39"
]
```

**Comment by divdax** [comment]
@sunel Any idea why slug is empty, or do you need any further informations to reproduce the problem?

**Comment by sunel** [comment]
@divdax 

Can you pull the latest tag and check.

**Comment by divdax** [comment]
@sunel 

✅pull
✅check
✅it works!
#### 🎉 Thank you! I really appreciate your work you put into this package!
