### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by avido** [sunel/eav#43]
Is this project still active ? as the releases still state 'beta'?
Is there a production release on schedule?

**Comment by sunel** [comment]
@avido 

Yes People have been using it and reporting issues.

Planning to release stable version by this month end.

**Comment by avido** [comment]
Good to hear!
Can't wait to see the production-ready release

**Comment by sunel** [comment]
https://github.com/sunel/eav/releases/tag/0.1.0
