### ISSUE TITLE
Flat command table names issue

### ISSUE THREAD

**Issue by avido** [sunel/eav#46]
When running the `$ php artisan eav:compile:entity [entity_code]` 

It can not find the schema information as my table-prefix is added to the information_schema table as well.

```
PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sclera_sclera_information_schema.columns' doesn't exist")
```

**Comment by sunel** [comment]
Added config to add table prefix in 0.2.1

https://github.com/sunel/eav/blob/master/config/eav.php#L68

Add the same to the published config file in `config/eav.php`

**Comment by avido** [comment]
> Added config to add table prefix in 0.2.1
> 
> https://github.com/sunel/eav/blob/master/config/eav.php#L68
> 
> Add the same to the published config file in `config/eav.php`

I think getting the prefix from database config is a more robust solution. As in my opinion the prefix shouldn't be set/changed on multiple locations
