### ISSUE TITLE
Laravel 7 suport

### ISSUE THREAD

**Issue by jonyw4** [sunel/eav#47]
Hi! 
This project will support Laravel 7? I tried install today but show me those messages.

![Captura de tela de 2020-03-29 18-11-04](https://user-images.githubusercontent.com/14056669/77861000-c930ee80-71e8-11ea-8995-0fc0edd3f971.png)

**Comment by sunel** [comment]
@jonyw4 

0.2.* has L7 Support

https://packagist.org/packages/sunel/eav
