### ISSUE TITLE
Have you consider it to make Nova Package

### ISSUE THREAD

**Issue by flakerimi** [sunel/eav#50]
Have you consider it to make Nova Package, I can contribute!

**Comment by sunel** [comment]
@flakerimi 

Right now no, but this package has a standalone  dashboard https://sunel.github.io/eav/master/dashboard.html

**Comment by flakerimi** [comment]
@sunel I tried to install it but its impossible, to many dependencies failed.

 Problem 1
    - sunel/eav-dashboard v0.0.2 requires sunel/eav ^0.1.0 -> satisfiable by sunel/eav[0.1.0, V0.1.0-beta.1, v0.1.0-beta.10, v0.1.0-beta.11, v0.1.0-beta.2, v0.1.0-beta.3, v0.1.0-beta.
    - The requested package laravel/framework (locked at v7.4.0, required as ^6.0) is satisfiable by laravel/framework[v7.4.0] but these conflict with your requirements or minimum-stability.
    - sunel/eav 0.2.1 requires sunel/json-api-resources >=0.0.1 -> satisfiable by sunel/json-api-resources[dev-master, v0.0.1, v0.0.2].

**Comment by sunel** [comment]
Try now i have pushed new version

**Comment by flakerimi** [comment]
- sunel/eav-dashboard v0.0.3 requires sunel/eav ^0.1.0 but these conflict with your requirements or minimum-stability
Shouldn't require v0.2.1,

**Comment by sunel** [comment]
Pushed https://github.com/sunel/eav-dashboard/releases/tag/v0.0.4

**Comment by flakerimi** [comment]
Back to orginal question, I see that dashboard is made of React, and nova request Vue.
With the popularity of nova getting bigger and bigger you should consider it. I am doing one with rinvex/laravel-attributes package then I saw your package which is better and heavily inspired from magento eav.

**Comment by sunel** [comment]
You can use the same api call from the dashboard  and create a nova package

**Comment by flakerimi** [comment]
Yes, thanks. 
Will get back when progress is made
