### ISSUE TITLE
dashboard not work

### ISSUE THREAD

**Issue by ipolovnikov** [sunel/eav#51]
hi
i find issues in your eav extension for laravel ^7.0
for new laravel version you nead fix 2 files in vendor **json-api-resources**

- in file src\Http\Resources\Json\Resource.php update extends from Resource on JsonResource

```
class Resource extends \Illuminate\Http\Resources\Json\Resource
class Resource extends \Illuminate\Http\Resources\Json\JsonResource
```

- file src\Http\Resources\Json\RelationshipResource.php

```
class RelationshipResource extends \Illuminate\Http\Resources\Json\Resource
class RelationshipResource extends \Illuminate\Http\Resources\Json\JsonResource
```
sanks for your eav

**Comment by sunel** [comment]
pull request ??

**Comment by sunel** [comment]
Fixed the issue https://github.com/sunel/json-api-resources/commit/361a62049ff27236a8d4f65a2afc663ca50b3ad8

use version v0.0.4
