### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by sathyashrayan** [sunel/eav#55]
Hello Sunel,

   I am finding the attached error in the extension . https://github.com/sunel/eav/blob/master/docs/master/dashboard.md 
   laraval version 6
![Screenshot from 2020-11-12 15-58-11](https://user-images.githubusercontent.com/4995301/98928763-2d968900-2500-11eb-8922-a9864a39b533.png)
![Screenshot from 2020-11-12 15-58-05](https://user-images.githubusercontent.com/4995301/98928774-2ff8e300-2500-11eb-87b1-e8a6221fc252.png)

**Comment by sunel** [comment]
@sathyashrayan 

can you post log from laravel
