### ISSUE TITLE
LV8 support

### ISSUE THREAD

**Issue by avido** [sunel/eav#59]
When is Laravel 8 support available ?

**Comment by mylemans** [comment]
@sunel I'm considering to use this package, but for now it seems defunct. Any ETA on laravel 8 support?

**Comment by sunel** [comment]
Sorry caught up with other works, will try to work on this weekend.

**Comment by sunel** [comment]
v 0.30 has L8 support now.

**Comment by avido** [comment]
Is the dashboard https://github.com/sunel/eav-dashboard also updated?

**Comment by sunel** [comment]
Its doesn't have any L8 dependency, So it must work
