### ISSUE TITLE
Add Attribute options

### ISSUE THREAD

**Issue by emayamca** [sunel/eav#6]
Can you explain how to add select and multiselect attribute options

**Comment by sunel** [comment]
To add a select option the few ways to do that, i will try to explain.

```php
Eav\Attribute::add([
    'attribute_code' => 'status',
    'entity_code' => 'product',
    'backend_class' => null,
    'backend_type' => 'int',
    'backend_table' =>  null,
    'frontend_class' =>  null,
    'frontend_type' => 'select', // Assgin the type "select"
    'frontend_label' => 'Status',
    'source_class' =>  Eav\Attribute\Source\Boolean::class, // check the [1]
    'default_value' => 0,
    'is_required' => 0,
    'required_validate_class' =>  null
]);
```

1. `source_class` is one way of getting the options values. Here you can assign a class that extends `Eav\Attribute\Source` 

check this [eav/src/Attribute/Source/Boolean.php](https://github.com/sunel/eav/blob/master/src/Attribute/Source/Boolean.php) file, this will provide 'yes' or 'No' options.

Another way is to add options using below **Recommended**

```php
Eav\Attribute::add([
    'attribute_code' => 'status',
    'entity_code' => 'product',
    'backend_class' => null,
    'backend_type' => 'int',
    'backend_table' =>  null,
    'frontend_class' =>  null,
    'frontend_type' => 'select', // Assgin the type "select"
    'frontend_label' => 'Status',
    'source_class' => null
    'options' => [
       '1' => 'Yes',
       '0'  => 'No'
     ]
    'default_value' => 0,
    'is_required' => 0,
    'required_validate_class' =>  null
]);
```

Or else you can also add directly to 

```php

$statusAttr = Eav\Attribute::findByCode('status', 'product');

Eav\AttributeOption::add($statusAttr, [
       '1' => 'Yes',
       '0'  => 'No'
]);
```

### To Get the Values

```php

$statusAttr = Eav\Attribute::findByCode('status', 'product');

$statusAttr->frontend_type
$statusAttr->options() 

```

**Comment by efs-tech** [comment]
Is there any way to store multiselect values?

**Comment by sunel** [comment]
Save the value as coma separated values and use

https://sunel.github.io/eav/master/snippet.html#custom-query

->whereRaw("FIND_IN_SET('css',tags)")

**Comment by joaopmmartins** [comment]
I am still not clear regarding to saving the select/multiselect values.
When you say to save the value as coma separated values, do you mean to save the value "css,tags" to the 'product_varchar' table? In select attribute do we store the value to the product_varchar table or the option id to the product_int? In multiselect attribute do we store the values or the option ids (comma separated) to the product_varchar table?

**Comment by sunel** [comment]
@joaopmmartins 

Yes you need to store the values as "css,js" in `varchar` if it fits and the use something like below

```php
$products = Products::select('*');

$attribute = Eav\Attribute::findByCode('tags', 'product');
$attribute->setEntity($products->baseEntity());

// Joining the attribute to the query, by default it will use inner join.
// In this case we need a left join.
$attribute->addAttributeJoin($products->getQuery(), 'left');

$attributeColumn = $attribute->getRawSelectColumn(); // tags_attr.value

$products->whereRaw("FIND_IN_SET('css',{$attributeColumn})")

$products->get();
```

**In multiselect attribute do we store the values or the option ids** for this, it can based on you need

You can use 2 attributes for this.

One To provide the options and another for saving the multiple options selected.

You have options to even store it in custom table https://sunel.github.io/eav/master/custom-table.html

**Comment by joaopmmartins** [comment]
I have an attribute called 'tags' in the 'attributes' table with the options 'css' ( id: 1 ), 'javascript' (id: 2) stored to the 'attribute_options' table.

attribute_options table:

ID   |   label |   value
=============
1     | CSS            |   css
2     | Javascript  |   javascript

Instead of storing the string 'css,javascript ', does it make any sense storing the options ids  '1,2' to the 'product_varchar' table, because the values already exist in the 'attribute_options' table? Whats your opinion?

**Comment by sunel** [comment]
@joaopmmartins 

Yes you can do that. 

attribute_options is a meta table for attribute if select type. You can use how every you need.

**Comment by sarbjeet-cmsDev** [comment]
@sunel it is amazing plugin for laravel Eav
-Here are my recommendation
*Add sort_order column to attributed entity so it is easy to sort
entity_attributes | sequence is not working since you do not store its value when map attribute to entity
*When fetch records, select value is not processing
*attribute_options add sort order field
*at coulum deleted_At to attributes for soft delete
* I did not found any documentation for backend_class

**Comment by sunel** [comment]
@sarbjeet-cmsDev 

**Add sort_order column to attributed entity so it is easy to sort**

https://sunel.github.io/eav/master/queries.html#where-clauses search for "orderByAttribute"

**Comment by divdax** [comment]
I also want to save multiple attribute values e.g. `['silver', 'black']` for `color`. It would be cool to save the model like so:

```php
$product = Product::first();
$product->color = ['silver', 'black'];
$product->save();
```

When adding a non existing color it should be created as a new option and just linked via the id.
