### ISSUE TITLE
How to work with facets correctly

### ISSUE THREAD

**Issue by maxyc** [sunel/eav#60]
I can't understand it. the example shows how to work with facets. but the example selects all attributes. and I need only those that are available in a specific category, with a specific filter. how can I do this? I have 500+ attributes, 4000+ products and it slows down a lot.

**Comment by sunel** [comment]
For each category you need to create a set https://sunel.github.io/eav/master/ideology/attribute-set.html
now each set will have n attributes. Map the set to your category.

Category -> set -> atributes

in the query selector you need to pass the attributes that you require https://sunel.github.io/eav/master/queries.html#selects
