### ISSUE TITLE
Unreachable statement in Model.php(335)

### ISSUE THREAD

**Issue by zambodaniel** [sunel/eav#61]
There are unreachable lines of code and also no syncChanges() are called in performUpdate() function.
Are there any reasons for this?

https://github.com/sunel/eav/blob/100805e61a646ee668918a09df39d1b6a628c93c/src/Model.php#L335

**Comment by sunel** [comment]
@zambodaniel  That should not happen, will look into it and push a fix.

**Comment by sunel** [comment]
Tagged https://github.com/sunel/eav/releases/tag/0.3.1
