### ISSUE TITLE
Can not add a product

### ISSUE THREAD

**Issue by Rukhsar** [sunel/eav#7]
I just followed your documentation. but when I create a product I get this error

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: insert into `bikes` (`name`, `sku`, `description`, `search`, `attribute_set_id`, `entity_id`, `updated_at`, `created_at`) values (Flight 2, FLG12, This is a bike sample description., 1, 1, 1, 2018-07-25 08:29:29, 2018-07-25 08:29:29))`

Obviously, I don't have the name, description and other fields in my bikes table. 

In your documentation you said 

**YOU NEED TO EDIT THE ATTRIBUTES INFO IN THE MIGRATION**

Can you please explain this to me.

**Comment by sunel** [comment]
@Rukhsar 

When you create a attribute the  `backend_type` is left empty, you need to updated it based on the type needed.

If the `backend_type` is empty it is considered  as static attributes ( column belong to main table ).

That is why i have a message saying the "YOU NEED TO EDIT THE ATTRIBUTES INFO IN THE MIGRATION"

**Comment by sunel** [comment]
@Rukhsar 

I am trying to improve the doc, suggestion are welcomed

**Comment by Rukhsar** [comment]
what should I assign that to make it work and use the EAV structure?

**Comment by sunel** [comment]
@Rukhsar 

Can you tell me which fields are considered  as attributes, so that i can explain you

**Comment by Rukhsar** [comment]
In our application, we want to have a new type which will store key values pairs. That's why I want to add a json field type. Also how I can make a flat table like I don't want to have different tables for types. 

`php artisan eav:compile:entity [entity_code]`

What this command will do.

**Comment by sunel** [comment]
@Rukhsar 

>If I want to register a new type like we have int, varchar, text how I can do that. I want to register a json field type

That is a tricky part, but there is a option hope it works,

you can find `backend_table`, it is empty but if you provide a table name, it will store the value in that table.

The table Schema should be 

```php
 Schema::create('json_type_table_name', function (Blueprint $table) {
            $table->increments('value_id')->comment('Value ID');
            $table->smallInteger('entity_type_id')->unsigned()->default(0)->comment('Entity Type ID');
            $table->integer('attribute_id')->unsigned()->default(0)->comment('Attribute ID');
            $table->integer('entity_id')->unsigned()->default(0)->comment('Entity ID');
            
            $table->json('value')->nullable()->comment('Value');
            
            $table->foreign('entity_id')
            	  ->references('id')->on('products') // changes this (this is main entity table )
				  ->onDelete('cascade');
            
            $table->unique(['entity_id','attribute_id']);
			$table->index('attribute_id');
			$table->index('entity_id');        	  
});

```

**Comment by sunel** [comment]
> I don't want to have different tables for types.

The props of EAV is for this, not sure why you chose it, if you want flat tables.

You can read this [When to Use](https://github.com/sunel/eav#when-to-use )

Meanwhile `php artisan eav:compile:entity` this is will collect all the values and make a flat table. you can use this if you have more reads to your database.

Its is like indexing.

**Comment by Rukhsar** [comment]
Thanks for the help.

Actually, we want to implement a bikes model as bikes come with a lot of different parts, so we want to use attributes to represent the components which can give us a bit flexibility to make custom attribute sets for different types of bikes.

I will use the flat table approach as we have over 1000 components to store.

Get work you have done on this package and you were very helpful as well.

Thanks again

**Comment by sunel** [comment]
Yeah as bikes is single entity in you application you can use the flat table approach and use some kind of search service.

EAV helps if you have bikes, cars, tools in the same application.

**Comment by Rukhsar** [comment]
Just a little question if you don't mind.

How we can grab all options added for a given attribute. For example, I have attribute colors and options added will be blue, red, black and so on. How I can list all those values for colors attribute.

Thanks

**Comment by sunel** [comment]
@Rukhsar 

https://github.com/sunel/eav/issues/6#issuecomment-402627983
