### ISSUE TITLE
how find all attribute of one id

### ISSUE THREAD

**Issue by namdaik** [sunel/eav#9]
Products::find(1)->all(['attr.*']); is wrong

**Comment by sunel** [comment]
```php
Products::select(['attr.*'])->find(1);
```

**Comment by kiru1978** [comment]
Hi I used your formula in that way
`Products::select(['attr.*'])->find($id);`
but i still have an array with all products.
I'm using Laravel 5.7

**Comment by sunel** [comment]
@kiru1978 

Can you recheck, i getting expected values.

if error still exist, kindly open new issue.

**Comment by kiru1978** [comment]
Hi @sunel 
Thanks for the reply. It works. 
Thanks again
